// Generated by tools/generate_sound_themes.py. All samples are original and local.
export const BUTTON_SOUNDS = {
  'tap': { asset: require('@/assets/sounds/soft-pop.wav'), volume: 0.28 },
  'navigate': { asset: require('@/assets/sounds/navigate.wav'), volume: 0.22 },
  'open': { asset: require('@/assets/sounds/open.wav'), volume: 0.27 },
  'close': { asset: require('@/assets/sounds/close.wav'), volume: 0.22 },
  'select': { asset: require('@/assets/sounds/select.wav'), volume: 0.2 },
  'increment': { asset: require('@/assets/sounds/increment.wav'), volume: 0.17 },
  'decrement': { asset: require('@/assets/sounds/decrement.wav'), volume: 0.17 },
  'confirm': { asset: require('@/assets/sounds/confirm.wav'), volume: 0.4 },
  'complete': { asset: require('@/assets/sounds/complete.wav'), volume: 0.42 },
  'delete': { asset: require('@/assets/sounds/delete.wav'), volume: 0.3 },
  'scan': { asset: require('@/assets/sounds/scan.wav'), volume: 0.32 },
  'voice': { asset: require('@/assets/sounds/voice.wav'), volume: 0.3 },
  'reward': { asset: require('@/assets/sounds/reward.wav'), volume: 0.34 },
  'primary': { asset: require('@/assets/sounds/primary.wav'), volume: 0.35 },
  'toggle-on': { asset: require('@/assets/sounds/toggle-on.wav'), volume: 0.22 },
  'toggle-off': { asset: require('@/assets/sounds/toggle-off.wav'), volume: 0.2 },
} as const;
export type ButtonSoundKind = keyof typeof BUTTON_SOUNDS;
export const BUTTON_SOUND_KINDS = Object.keys(BUTTON_SOUNDS) as ButtonSoundKind[];

export const SOUND_EFFECTS = {
  'tap': { asset: BUTTON_SOUNDS['tap'].asset, resource: 'assets_sounds_softpop', theme: 'classic', label: 'sound_action_tap' },
  'navigate': { asset: BUTTON_SOUNDS['navigate'].asset, resource: 'assets_sounds_navigate', theme: 'classic', label: 'sound_action_navigate' },
  'open': { asset: BUTTON_SOUNDS['open'].asset, resource: 'assets_sounds_open', theme: 'classic', label: 'sound_action_open' },
  'close': { asset: BUTTON_SOUNDS['close'].asset, resource: 'assets_sounds_close', theme: 'classic', label: 'sound_action_close' },
  'select': { asset: BUTTON_SOUNDS['select'].asset, resource: 'assets_sounds_select', theme: 'classic', label: 'sound_action_select' },
  'increment': { asset: BUTTON_SOUNDS['increment'].asset, resource: 'assets_sounds_increment', theme: 'classic', label: 'sound_action_increment' },
  'decrement': { asset: BUTTON_SOUNDS['decrement'].asset, resource: 'assets_sounds_decrement', theme: 'classic', label: 'sound_action_decrement' },
  'confirm': { asset: BUTTON_SOUNDS['confirm'].asset, resource: 'assets_sounds_confirm', theme: 'classic', label: 'sound_action_confirm' },
  'complete': { asset: BUTTON_SOUNDS['complete'].asset, resource: 'assets_sounds_complete', theme: 'classic', label: 'sound_action_complete' },
  'delete': { asset: BUTTON_SOUNDS['delete'].asset, resource: 'assets_sounds_delete', theme: 'classic', label: 'sound_action_delete' },
  'scan': { asset: BUTTON_SOUNDS['scan'].asset, resource: 'assets_sounds_scan', theme: 'classic', label: 'sound_action_scan' },
  'voice': { asset: BUTTON_SOUNDS['voice'].asset, resource: 'assets_sounds_voice', theme: 'classic', label: 'sound_action_voice' },
  'reward': { asset: BUTTON_SOUNDS['reward'].asset, resource: 'assets_sounds_reward', theme: 'classic', label: 'sound_action_reward' },
  'primary': { asset: BUTTON_SOUNDS['primary'].asset, resource: 'assets_sounds_primary', theme: 'classic', label: 'sound_action_primary' },
  'toggle-on': { asset: BUTTON_SOUNDS['toggle-on'].asset, resource: 'assets_sounds_toggleon', theme: 'classic', label: 'sound_action_toggle_on' },
  'toggle-off': { asset: BUTTON_SOUNDS['toggle-off'].asset, resource: 'assets_sounds_toggleoff', theme: 'classic', label: 'sound_action_toggle_off' },
  'minimal-tap': { asset: require('@/assets/sounds/minimal-tap.wav'), resource: 'assets_sounds_minimaltap', theme: 'minimal', label: 'sound_effect_tap' },
  'minimal-up': { asset: require('@/assets/sounds/minimal-up.wav'), resource: 'assets_sounds_minimalup', theme: 'minimal', label: 'sound_effect_up' },
  'minimal-down': { asset: require('@/assets/sounds/minimal-down.wav'), resource: 'assets_sounds_minimaldown', theme: 'minimal', label: 'sound_effect_down' },
  'minimal-confirm': { asset: require('@/assets/sounds/minimal-confirm.wav'), resource: 'assets_sounds_minimalconfirm', theme: 'minimal', label: 'sound_effect_confirm' },
  'minimal-complete': { asset: require('@/assets/sounds/minimal-complete.wav'), resource: 'assets_sounds_minimalcomplete', theme: 'minimal', label: 'sound_effect_complete' },
  'minimal-delete': { asset: require('@/assets/sounds/minimal-delete.wav'), resource: 'assets_sounds_minimaldelete', theme: 'minimal', label: 'sound_effect_delete' },
  'minimal-scan': { asset: require('@/assets/sounds/minimal-scan.wav'), resource: 'assets_sounds_minimalscan', theme: 'minimal', label: 'sound_effect_scan' },
  'minimal-voice': { asset: require('@/assets/sounds/minimal-voice.wav'), resource: 'assets_sounds_minimalvoice', theme: 'minimal', label: 'sound_effect_voice' },
  'nature-tap': { asset: require('@/assets/sounds/nature-tap.wav'), resource: 'assets_sounds_naturetap', theme: 'nature', label: 'sound_effect_tap' },
  'nature-up': { asset: require('@/assets/sounds/nature-up.wav'), resource: 'assets_sounds_natureup', theme: 'nature', label: 'sound_effect_up' },
  'nature-down': { asset: require('@/assets/sounds/nature-down.wav'), resource: 'assets_sounds_naturedown', theme: 'nature', label: 'sound_effect_down' },
  'nature-confirm': { asset: require('@/assets/sounds/nature-confirm.wav'), resource: 'assets_sounds_natureconfirm', theme: 'nature', label: 'sound_effect_confirm' },
  'nature-complete': { asset: require('@/assets/sounds/nature-complete.wav'), resource: 'assets_sounds_naturecomplete', theme: 'nature', label: 'sound_effect_complete' },
  'nature-delete': { asset: require('@/assets/sounds/nature-delete.wav'), resource: 'assets_sounds_naturedelete', theme: 'nature', label: 'sound_effect_delete' },
  'nature-scan': { asset: require('@/assets/sounds/nature-scan.wav'), resource: 'assets_sounds_naturescan', theme: 'nature', label: 'sound_effect_scan' },
  'nature-voice': { asset: require('@/assets/sounds/nature-voice.wav'), resource: 'assets_sounds_naturevoice', theme: 'nature', label: 'sound_effect_voice' },
  'water-tap': { asset: require('@/assets/sounds/water-tap.wav'), resource: 'assets_sounds_watertap', theme: 'water', label: 'sound_effect_tap' },
  'water-up': { asset: require('@/assets/sounds/water-up.wav'), resource: 'assets_sounds_waterup', theme: 'water', label: 'sound_effect_up' },
  'water-down': { asset: require('@/assets/sounds/water-down.wav'), resource: 'assets_sounds_waterdown', theme: 'water', label: 'sound_effect_down' },
  'water-confirm': { asset: require('@/assets/sounds/water-confirm.wav'), resource: 'assets_sounds_waterconfirm', theme: 'water', label: 'sound_effect_confirm' },
  'water-complete': { asset: require('@/assets/sounds/water-complete.wav'), resource: 'assets_sounds_watercomplete', theme: 'water', label: 'sound_effect_complete' },
  'water-delete': { asset: require('@/assets/sounds/water-delete.wav'), resource: 'assets_sounds_waterdelete', theme: 'water', label: 'sound_effect_delete' },
  'water-scan': { asset: require('@/assets/sounds/water-scan.wav'), resource: 'assets_sounds_waterscan', theme: 'water', label: 'sound_effect_scan' },
  'water-voice': { asset: require('@/assets/sounds/water-voice.wav'), resource: 'assets_sounds_watervoice', theme: 'water', label: 'sound_effect_voice' },
  'christmas-tap': { asset: require('@/assets/sounds/christmas-tap.wav'), resource: 'assets_sounds_christmastap', theme: 'christmas', label: 'sound_effect_tap' },
  'christmas-up': { asset: require('@/assets/sounds/christmas-up.wav'), resource: 'assets_sounds_christmasup', theme: 'christmas', label: 'sound_effect_up' },
  'christmas-down': { asset: require('@/assets/sounds/christmas-down.wav'), resource: 'assets_sounds_christmasdown', theme: 'christmas', label: 'sound_effect_down' },
  'christmas-confirm': { asset: require('@/assets/sounds/christmas-confirm.wav'), resource: 'assets_sounds_christmasconfirm', theme: 'christmas', label: 'sound_effect_confirm' },
  'christmas-complete': { asset: require('@/assets/sounds/christmas-complete.wav'), resource: 'assets_sounds_christmascomplete', theme: 'christmas', label: 'sound_effect_complete' },
  'christmas-delete': { asset: require('@/assets/sounds/christmas-delete.wav'), resource: 'assets_sounds_christmasdelete', theme: 'christmas', label: 'sound_effect_delete' },
  'christmas-scan': { asset: require('@/assets/sounds/christmas-scan.wav'), resource: 'assets_sounds_christmasscan', theme: 'christmas', label: 'sound_effect_scan' },
  'christmas-voice': { asset: require('@/assets/sounds/christmas-voice.wav'), resource: 'assets_sounds_christmasvoice', theme: 'christmas', label: 'sound_effect_voice' },
  'halloween-tap': { asset: require('@/assets/sounds/halloween-tap.wav'), resource: 'assets_sounds_halloweentap', theme: 'halloween', label: 'sound_effect_tap' },
  'halloween-up': { asset: require('@/assets/sounds/halloween-up.wav'), resource: 'assets_sounds_halloweenup', theme: 'halloween', label: 'sound_effect_up' },
  'halloween-down': { asset: require('@/assets/sounds/halloween-down.wav'), resource: 'assets_sounds_halloweendown', theme: 'halloween', label: 'sound_effect_down' },
  'halloween-confirm': { asset: require('@/assets/sounds/halloween-confirm.wav'), resource: 'assets_sounds_halloweenconfirm', theme: 'halloween', label: 'sound_effect_confirm' },
  'halloween-complete': { asset: require('@/assets/sounds/halloween-complete.wav'), resource: 'assets_sounds_halloweencomplete', theme: 'halloween', label: 'sound_effect_complete' },
  'halloween-delete': { asset: require('@/assets/sounds/halloween-delete.wav'), resource: 'assets_sounds_halloweendelete', theme: 'halloween', label: 'sound_effect_delete' },
  'halloween-scan': { asset: require('@/assets/sounds/halloween-scan.wav'), resource: 'assets_sounds_halloweenscan', theme: 'halloween', label: 'sound_effect_scan' },
  'halloween-voice': { asset: require('@/assets/sounds/halloween-voice.wav'), resource: 'assets_sounds_halloweenvoice', theme: 'halloween', label: 'sound_effect_voice' },
  'horror-tap': { asset: require('@/assets/sounds/horror-tap.wav'), resource: 'assets_sounds_horrortap', theme: 'horror', label: 'sound_effect_tap' },
  'horror-up': { asset: require('@/assets/sounds/horror-up.wav'), resource: 'assets_sounds_horrorup', theme: 'horror', label: 'sound_effect_up' },
  'horror-down': { asset: require('@/assets/sounds/horror-down.wav'), resource: 'assets_sounds_horrordown', theme: 'horror', label: 'sound_effect_down' },
  'horror-confirm': { asset: require('@/assets/sounds/horror-confirm.wav'), resource: 'assets_sounds_horrorconfirm', theme: 'horror', label: 'sound_effect_confirm' },
  'horror-complete': { asset: require('@/assets/sounds/horror-complete.wav'), resource: 'assets_sounds_horrorcomplete', theme: 'horror', label: 'sound_effect_complete' },
  'horror-delete': { asset: require('@/assets/sounds/horror-delete.wav'), resource: 'assets_sounds_horrordelete', theme: 'horror', label: 'sound_effect_delete' },
  'horror-scan': { asset: require('@/assets/sounds/horror-scan.wav'), resource: 'assets_sounds_horrorscan', theme: 'horror', label: 'sound_effect_scan' },
  'horror-voice': { asset: require('@/assets/sounds/horror-voice.wav'), resource: 'assets_sounds_horrorvoice', theme: 'horror', label: 'sound_effect_voice' },
  'space-tap': { asset: require('@/assets/sounds/space-tap.wav'), resource: 'assets_sounds_spacetap', theme: 'space', label: 'sound_effect_tap' },
  'space-up': { asset: require('@/assets/sounds/space-up.wav'), resource: 'assets_sounds_spaceup', theme: 'space', label: 'sound_effect_up' },
  'space-down': { asset: require('@/assets/sounds/space-down.wav'), resource: 'assets_sounds_spacedown', theme: 'space', label: 'sound_effect_down' },
  'space-confirm': { asset: require('@/assets/sounds/space-confirm.wav'), resource: 'assets_sounds_spaceconfirm', theme: 'space', label: 'sound_effect_confirm' },
  'space-complete': { asset: require('@/assets/sounds/space-complete.wav'), resource: 'assets_sounds_spacecomplete', theme: 'space', label: 'sound_effect_complete' },
  'space-delete': { asset: require('@/assets/sounds/space-delete.wav'), resource: 'assets_sounds_spacedelete', theme: 'space', label: 'sound_effect_delete' },
  'space-scan': { asset: require('@/assets/sounds/space-scan.wav'), resource: 'assets_sounds_spacescan', theme: 'space', label: 'sound_effect_scan' },
  'space-voice': { asset: require('@/assets/sounds/space-voice.wav'), resource: 'assets_sounds_spacevoice', theme: 'space', label: 'sound_effect_voice' },
  'arcade-tap': { asset: require('@/assets/sounds/arcade-tap.wav'), resource: 'assets_sounds_arcadetap', theme: 'arcade', label: 'sound_effect_tap' },
  'arcade-up': { asset: require('@/assets/sounds/arcade-up.wav'), resource: 'assets_sounds_arcadeup', theme: 'arcade', label: 'sound_effect_up' },
  'arcade-down': { asset: require('@/assets/sounds/arcade-down.wav'), resource: 'assets_sounds_arcadedown', theme: 'arcade', label: 'sound_effect_down' },
  'arcade-confirm': { asset: require('@/assets/sounds/arcade-confirm.wav'), resource: 'assets_sounds_arcadeconfirm', theme: 'arcade', label: 'sound_effect_confirm' },
  'arcade-complete': { asset: require('@/assets/sounds/arcade-complete.wav'), resource: 'assets_sounds_arcadecomplete', theme: 'arcade', label: 'sound_effect_complete' },
  'arcade-delete': { asset: require('@/assets/sounds/arcade-delete.wav'), resource: 'assets_sounds_arcadedelete', theme: 'arcade', label: 'sound_effect_delete' },
  'arcade-scan': { asset: require('@/assets/sounds/arcade-scan.wav'), resource: 'assets_sounds_arcadescan', theme: 'arcade', label: 'sound_effect_scan' },
  'arcade-voice': { asset: require('@/assets/sounds/arcade-voice.wav'), resource: 'assets_sounds_arcadevoice', theme: 'arcade', label: 'sound_effect_voice' },
  'comic-tap': { asset: require('@/assets/sounds/comic-tap.wav'), resource: 'assets_sounds_comictap', theme: 'comic', label: 'sound_effect_tap' },
  'comic-up': { asset: require('@/assets/sounds/comic-up.wav'), resource: 'assets_sounds_comicup', theme: 'comic', label: 'sound_effect_up' },
  'comic-down': { asset: require('@/assets/sounds/comic-down.wav'), resource: 'assets_sounds_comicdown', theme: 'comic', label: 'sound_effect_down' },
  'comic-confirm': { asset: require('@/assets/sounds/comic-confirm.wav'), resource: 'assets_sounds_comicconfirm', theme: 'comic', label: 'sound_effect_confirm' },
  'comic-complete': { asset: require('@/assets/sounds/comic-complete.wav'), resource: 'assets_sounds_comiccomplete', theme: 'comic', label: 'sound_effect_complete' },
  'comic-delete': { asset: require('@/assets/sounds/comic-delete.wav'), resource: 'assets_sounds_comicdelete', theme: 'comic', label: 'sound_effect_delete' },
  'comic-scan': { asset: require('@/assets/sounds/comic-scan.wav'), resource: 'assets_sounds_comicscan', theme: 'comic', label: 'sound_effect_scan' },
  'comic-voice': { asset: require('@/assets/sounds/comic-voice.wav'), resource: 'assets_sounds_comicvoice', theme: 'comic', label: 'sound_effect_voice' },
  'raspberry-tap': { asset: require('@/assets/sounds/raspberry-tap.wav'), resource: 'assets_sounds_raspberrytap', theme: 'raspberry', label: 'sound_effect_tap' },
  'raspberry-up': { asset: require('@/assets/sounds/raspberry-up.wav'), resource: 'assets_sounds_raspberryup', theme: 'raspberry', label: 'sound_effect_up' },
  'raspberry-down': { asset: require('@/assets/sounds/raspberry-down.wav'), resource: 'assets_sounds_raspberrydown', theme: 'raspberry', label: 'sound_effect_down' },
  'raspberry-confirm': { asset: require('@/assets/sounds/raspberry-confirm.wav'), resource: 'assets_sounds_raspberryconfirm', theme: 'raspberry', label: 'sound_effect_confirm' },
  'raspberry-complete': { asset: require('@/assets/sounds/raspberry-complete.wav'), resource: 'assets_sounds_raspberrycomplete', theme: 'raspberry', label: 'sound_effect_complete' },
  'raspberry-delete': { asset: require('@/assets/sounds/raspberry-delete.wav'), resource: 'assets_sounds_raspberrydelete', theme: 'raspberry', label: 'sound_effect_delete' },
  'raspberry-scan': { asset: require('@/assets/sounds/raspberry-scan.wav'), resource: 'assets_sounds_raspberryscan', theme: 'raspberry', label: 'sound_effect_scan' },
  'raspberry-voice': { asset: require('@/assets/sounds/raspberry-voice.wav'), resource: 'assets_sounds_raspberryvoice', theme: 'raspberry', label: 'sound_effect_voice' },
  'fart-tap': { asset: require('@/assets/sounds/fart-tap.wav'), resource: 'assets_sounds_farttap', theme: 'fart', label: 'sound_effect_tap' },
  'fart-up': { asset: require('@/assets/sounds/fart-up.wav'), resource: 'assets_sounds_fartup', theme: 'fart', label: 'sound_effect_up' },
  'fart-down': { asset: require('@/assets/sounds/fart-down.wav'), resource: 'assets_sounds_fartdown', theme: 'fart', label: 'sound_effect_down' },
  'fart-confirm': { asset: require('@/assets/sounds/fart-confirm.wav'), resource: 'assets_sounds_fartconfirm', theme: 'fart', label: 'sound_effect_confirm' },
  'fart-complete': { asset: require('@/assets/sounds/fart-complete.wav'), resource: 'assets_sounds_fartcomplete', theme: 'fart', label: 'sound_effect_complete' },
  'fart-delete': { asset: require('@/assets/sounds/fart-delete.wav'), resource: 'assets_sounds_fartdelete', theme: 'fart', label: 'sound_effect_delete' },
  'fart-scan': { asset: require('@/assets/sounds/fart-scan.wav'), resource: 'assets_sounds_fartscan', theme: 'fart', label: 'sound_effect_scan' },
  'fart-voice': { asset: require('@/assets/sounds/fart-voice.wav'), resource: 'assets_sounds_fartvoice', theme: 'fart', label: 'sound_effect_voice' },
} as const;
export type SoundEffectId = keyof typeof SOUND_EFFECTS;

export const SOUND_THEMES = [
  { id: 'classic', label: 'sound_theme_classic', emoji: '✨', color: '#B4CF42', cues: { 'tap': 'tap', 'navigate': 'navigate', 'open': 'open', 'close': 'close', 'select': 'select', 'increment': 'increment', 'decrement': 'decrement', 'confirm': 'confirm', 'complete': 'complete', 'delete': 'delete', 'scan': 'scan', 'voice': 'voice', 'reward': 'reward', 'primary': 'primary', 'toggle-on': 'toggle-on', 'toggle-off': 'toggle-off' } },
  { id: 'minimal', label: 'sound_theme_minimal', emoji: '🫧', color: '#9CB6C6', cues: { 'tap': 'minimal-tap', 'navigate': 'minimal-tap', 'open': 'minimal-up', 'close': 'minimal-down', 'select': 'minimal-tap', 'increment': 'minimal-up', 'decrement': 'minimal-down', 'confirm': 'minimal-confirm', 'complete': 'minimal-complete', 'delete': 'minimal-delete', 'scan': 'minimal-scan', 'voice': 'minimal-voice', 'reward': 'minimal-complete', 'primary': 'minimal-confirm', 'toggle-on': 'minimal-up', 'toggle-off': 'minimal-down' } },
  { id: 'nature', label: 'sound_theme_nature', emoji: '🌿', color: '#7BCB95', cues: { 'tap': 'nature-tap', 'navigate': 'nature-tap', 'open': 'nature-up', 'close': 'nature-down', 'select': 'nature-tap', 'increment': 'nature-up', 'decrement': 'nature-down', 'confirm': 'nature-confirm', 'complete': 'nature-complete', 'delete': 'nature-delete', 'scan': 'nature-scan', 'voice': 'nature-voice', 'reward': 'nature-complete', 'primary': 'nature-confirm', 'toggle-on': 'nature-up', 'toggle-off': 'nature-down' } },
  { id: 'water', label: 'sound_theme_water', emoji: '💧', color: '#79C6ED', cues: { 'tap': 'water-tap', 'navigate': 'water-tap', 'open': 'water-up', 'close': 'water-down', 'select': 'water-tap', 'increment': 'water-up', 'decrement': 'water-down', 'confirm': 'water-confirm', 'complete': 'water-complete', 'delete': 'water-delete', 'scan': 'water-scan', 'voice': 'water-voice', 'reward': 'water-complete', 'primary': 'water-confirm', 'toggle-on': 'water-up', 'toggle-off': 'water-down' } },
  { id: 'christmas', label: 'sound_theme_christmas', emoji: '🎄', color: '#E7B653', cues: { 'tap': 'christmas-tap', 'navigate': 'christmas-tap', 'open': 'christmas-up', 'close': 'christmas-down', 'select': 'christmas-tap', 'increment': 'christmas-up', 'decrement': 'christmas-down', 'confirm': 'christmas-confirm', 'complete': 'christmas-complete', 'delete': 'christmas-delete', 'scan': 'christmas-scan', 'voice': 'christmas-voice', 'reward': 'christmas-complete', 'primary': 'christmas-confirm', 'toggle-on': 'christmas-up', 'toggle-off': 'christmas-down' } },
  { id: 'halloween', label: 'sound_theme_halloween', emoji: '🎃', color: '#ECA05C', cues: { 'tap': 'halloween-tap', 'navigate': 'halloween-tap', 'open': 'halloween-up', 'close': 'halloween-down', 'select': 'halloween-tap', 'increment': 'halloween-up', 'decrement': 'halloween-down', 'confirm': 'halloween-confirm', 'complete': 'halloween-complete', 'delete': 'halloween-delete', 'scan': 'halloween-scan', 'voice': 'halloween-voice', 'reward': 'halloween-complete', 'primary': 'halloween-confirm', 'toggle-on': 'halloween-up', 'toggle-off': 'halloween-down' } },
  { id: 'horror', label: 'sound_theme_horror', emoji: '👻', color: '#BE9DEB', cues: { 'tap': 'horror-tap', 'navigate': 'horror-tap', 'open': 'horror-up', 'close': 'horror-down', 'select': 'horror-tap', 'increment': 'horror-up', 'decrement': 'horror-down', 'confirm': 'horror-confirm', 'complete': 'horror-complete', 'delete': 'horror-delete', 'scan': 'horror-scan', 'voice': 'horror-voice', 'reward': 'horror-complete', 'primary': 'horror-confirm', 'toggle-on': 'horror-up', 'toggle-off': 'horror-down' } },
  { id: 'space', label: 'sound_theme_space', emoji: '🛸', color: '#97ACFF', cues: { 'tap': 'space-tap', 'navigate': 'space-tap', 'open': 'space-up', 'close': 'space-down', 'select': 'space-tap', 'increment': 'space-up', 'decrement': 'space-down', 'confirm': 'space-confirm', 'complete': 'space-complete', 'delete': 'space-delete', 'scan': 'space-scan', 'voice': 'space-voice', 'reward': 'space-complete', 'primary': 'space-confirm', 'toggle-on': 'space-up', 'toggle-off': 'space-down' } },
  { id: 'arcade', label: 'sound_theme_arcade', emoji: '👾', color: '#ECA0E0', cues: { 'tap': 'arcade-tap', 'navigate': 'arcade-tap', 'open': 'arcade-up', 'close': 'arcade-down', 'select': 'arcade-tap', 'increment': 'arcade-up', 'decrement': 'arcade-down', 'confirm': 'arcade-confirm', 'complete': 'arcade-complete', 'delete': 'arcade-delete', 'scan': 'arcade-scan', 'voice': 'arcade-voice', 'reward': 'arcade-complete', 'primary': 'arcade-confirm', 'toggle-on': 'arcade-up', 'toggle-off': 'arcade-down' } },
  { id: 'comic', label: 'sound_theme_comic', emoji: '🤡', color: '#F2D575', cues: { 'tap': 'comic-tap', 'navigate': 'comic-tap', 'open': 'comic-up', 'close': 'comic-down', 'select': 'comic-tap', 'increment': 'comic-up', 'decrement': 'comic-down', 'confirm': 'comic-confirm', 'complete': 'comic-complete', 'delete': 'comic-delete', 'scan': 'comic-scan', 'voice': 'comic-voice', 'reward': 'comic-complete', 'primary': 'comic-confirm', 'toggle-on': 'comic-up', 'toggle-off': 'comic-down' } },
  { id: 'raspberry', label: 'sound_theme_raspberry', emoji: '😝', color: '#ED9AAF', cues: { 'tap': 'raspberry-tap', 'navigate': 'raspberry-tap', 'open': 'raspberry-up', 'close': 'raspberry-down', 'select': 'raspberry-tap', 'increment': 'raspberry-up', 'decrement': 'raspberry-down', 'confirm': 'raspberry-confirm', 'complete': 'raspberry-complete', 'delete': 'raspberry-delete', 'scan': 'raspberry-scan', 'voice': 'raspberry-voice', 'reward': 'raspberry-complete', 'primary': 'raspberry-confirm', 'toggle-on': 'raspberry-up', 'toggle-off': 'raspberry-down' } },
  { id: 'fart', label: 'sound_theme_fart', emoji: '💨', color: '#BEBD7C', cues: { 'tap': 'fart-tap', 'navigate': 'fart-tap', 'open': 'fart-up', 'close': 'fart-down', 'select': 'fart-tap', 'increment': 'fart-up', 'decrement': 'fart-down', 'confirm': 'fart-confirm', 'complete': 'fart-complete', 'delete': 'fart-delete', 'scan': 'fart-scan', 'voice': 'fart-voice', 'reward': 'fart-complete', 'primary': 'fart-confirm', 'toggle-on': 'fart-up', 'toggle-off': 'fart-down' } },
] as const;
export type SoundThemeId = typeof SOUND_THEMES[number]['id'];

export type SoundChoice = SoundEffectId | 'silent';
export interface ButtonSoundPreferences {
  theme: SoundThemeId;
  overrides: Partial<Record<ButtonSoundKind, SoundChoice>>;
}
export const DEFAULT_SOUND_PREFERENCES: ButtonSoundPreferences = { theme: 'classic', overrides: {} };

export function resolveButtonSound(kind: ButtonSoundKind, preferences: ButtonSoundPreferences): SoundChoice {
  const theme = SOUND_THEMES.find(item => item.id === preferences.theme) || SOUND_THEMES[0];
  return preferences.overrides[kind] ?? theme.cues[kind];
}

export function sanitizeSoundPreferences(raw: unknown): ButtonSoundPreferences {
  if (!raw || typeof raw !== 'object') return { theme: 'classic', overrides: {} };
  const value = raw as Record<string, unknown>;
  const theme = SOUND_THEMES.find(item => item.id === value.theme)?.id || 'classic';
  const overrides: ButtonSoundPreferences['overrides'] = {};
  if (value.overrides && typeof value.overrides === 'object') {
    for (const kind of BUTTON_SOUND_KINDS) {
      const effect = (value.overrides as Record<string, unknown>)[kind];
      if (effect === 'silent' || (typeof effect === 'string' && Object.hasOwn(SOUND_EFFECTS, effect))) {
        overrides[kind] = effect as SoundChoice;
      }
    }
  }
  return { theme, overrides };
}
